services:
  petclinic-app:
    image: spring-petclinic-rest:latest
    ports:
      - "9966:9966"
    environment:
      SERVER_PORT: "9966"
      SPRING_SQL_INIT.MODE: always
      WHATAP_CONF: |
        license=x2m0gmm4mept9-z3v53gikg3ruif-z7au72rutah58g
        whatap.server.host=13.124.188.156
        logsink_enabled=true
        weaving=spring-boot-3.0
        dbc_sid_enabled=truehook_db_native_enabled
        hook_db_native_enabled=truehook_db_native_enabled
        debug_dbc_sid_enabled=true
