services:
  petclinic-mysql:
    image: mysql:8.0
    hostname: petclinic-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: petclinic
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic
  whatap_db_agent:
    image: whatap/db-agent:latest
    container_name: "whatap_db_agent"
    environment:
      WHATAP_CONF: |
        license=x2m8gbge5032d-x1kt9iokh3pvpg-x6uevo4npkh1i3
        whatap.server.host=13.124.188.156
        dbms=mysql
        db_ip=petclinic-mysql
        db_port=3306
        connect_option=?useSSL=false&allowPublicKeyRetrieval=true
      DB_USERNAME: root
      DB_PASSWORD: petclinic
    restart: on-failure
    depends_on:
      - petclinic-mysql
  petclinic-app:
    image: spring-petclinic-rest:latest
    hostname: petclinic-app
    ports:
      - "9966:9966"
    environment:
      SPRING_PROFILES_ACTIVE: mysql,spring-data-jpa
      DATABASE: mysql
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_DATASOURCE_URL: jdbc:mysql://petclinic-mysql:3306/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
      SPRING_SQL_INIT.MODE: always
      SERVER_PORT: "9966"
      WHATAP_CONF: |
        license=x2m0gmm4mept9-z3v53gikg3ruif-z7au72rutah58g
        whatap.server.host=13.124.188.156
        logsink_enabled=true
        weaving=spring-boot-3.0
        dbc_sid_enabled=true
        hook_db_native_enabled=true
        debug_dbc_sid_enabled=true
    depends_on:
      - petclinic-mysql
    restart: on-failure
  petclinic-client-01:
    image: spring-petclinic-rest-client:latest
    environment:
      PETCLINIC_URL: http://petclinic-app:9966
      NUM_WORKERS: 1
    restart: on-failure
    depends_on:
      - petclinic-mysql
      - petclinic-app
  petclinic-client-02:
    image: spring-petclinic-rest-client:latest
    environment:
      PETCLINIC_URL: http://petclinic-app:9966
      NUM_WORKERS: 1
    restart: on-failure
    depends_on:
      - petclinic-mysql
      - petclinic-app
      - petclinic-client-01
  petclinic-client-03:
    image: spring-petclinic-rest-client:latest
    environment:
      PETCLINIC_URL: http://petclinic-app:9966
      NUM_WORKERS: 1
    restart: on-failure
    depends_on:
      - petclinic-mysql
      - petclinic-app
      - petclinic-client-02
